development:
 database:
  host: master.openpaas.co.kr
  port: 27017
  username: porgex
  password: porgex@123
  dbname: porgex_master
 tcp:
  port: :3001
  host : 127.0.0.1
 common:
  logfile: log
  loglevel: debug
 daemon:
  pidfilename: porgex-node.pid
  pidfileperm: 0644
  logfilename: porgex-node.log
  logfilePerm: 0640
  workdir: ./
  umask: 027
  args: [porgex-node-client daemon]